- hosts: jitsi
  vars:
    jitsi_config:
      JICOFO_AUTH_PASSWORD: "{{ jicofo_auth_password }}"
      JVB_AUTH_PASSWORD: "{{ jvb_auth_password }}"
      JIGASI_XMPP_PASSWORD: "{{ jigasi_xmpp_password }}"
      JIBRI_RECORDER_PASSWORD: "{{ jibri_recorder_password }}"
      JIBRI_XMPP_PASSWORD: "{{ jibri_xmpp_password }}"
      PUBLIC_URL: "https://{{ jitsi_domain }}"
      ENABLE_LETSENCRYPT: 1
      LETSENCRYPT_DOMAIN: "{{ jitsi_domain }}"
      LETSENCRYPT_EMAIL: "{{ letsencrypt_email }}"
      LETSENCRYPT_USE_STAGING: 0
      HTTP_PORT: 80
      HTTPS_PORT: 443
    jitsi_docker_jitsi_meet_docker_compose_override:
      version: "3.0"
      services:
        web:
          volumes:
            - "{{ jitsi_streaming_client_dir }}/dist:/usr/share/jitsi-meet/streamer:Z"
    jitsi_streaming_client_dir: /root/src/jitsi-streaming-client
  roles:
    - nodejs
    - jitsi-streaming-client
    - docker
    - jitsi